### PR TITLE
Set correct Content-Type header

### LINKED ISSUE #1: Wrong content-type
The HTTP content-type header is set to "text/html" rather than "application/xml".

You can try this on bitmidi.com.

```
❯ curl -i https://bitmidi.com/sitemap.xml
HTTP/2 200 
server: nginx
date: Fri, 09 Nov 2018 14:18:21 GMT
content-type: text/html; charset=utf-8
content-length: 445
vary: Accept-Encoding
x-content-type-options: nosniff
referrer-policy: strict-origin-when-cross-origin
strict-transport-security: max-age=31536000; includeSubDomains; preload
etag: W/"1bd-2bBiOMomgckrx3C9S+h6fksNNNc"

<?xml version="1.0" encoding="utf-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://bitmidi.com/sitemap-0.xml</loc>
    <lastmod>2018-11-08</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://bitmidi.com/sitemap-1.xml</loc>
    <lastmod>2018-11-08</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://bitmidi.com/sitemap-2.xml</loc>
    <lastmod>2018-11-08</lastmod>
  </sitemap>
</sitemapindex>
```

### PR DESCRIPTION
**Pull request by lydell**
Fixes #1.

Tested manually.

### CODE REVIEW

**Comment by lydell** [comment]
@feross Friendly ping :)

([bitmidi.com/sitemap.xml is not valid](https://www.xml-sitemaps.com/validate-xml-sitemap.html?op=validate-xml-sitemap&go=1&sitemapurl=https%3A%2F%2Fbitmidi.com%2Fsitemap.xml&submit=Validate+Sitemap))

**Comment by lydell** [comment]
@feross If you have the time, merging this would be a nice Christmas present, because this library is very useful :)

**Comment by lydell** [comment]
@feross Friendly ping :) As a reminder, this PR changes the content-type from text/html to application/xml since sitemap.xml is an XML file :)

**Review by feross — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
